# Generated by Django 4.2.19 on 2025-02-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nails', '0004_alter_customuser_managers_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='nailsample',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
